### ISSUE TITLE
schema_tables_with_full_table_scans seems to now show the row count properly

### ISSUE THREAD

**Issue by sjmudd** [MarkLeith/mysql-sys#8] opened 2014-04-30 11:21 UTC
I have a script collecting information from this sys view and others:

```
Apr 30 13:15:58 myserver log_sys_data[18681]: view: sys.schema_tables_with_full_table_scans:
+---------------+----------------------------------------+-------------------+
| object_schema | object_name                            | rows_full_scanned |
+---------------+----------------------------------------+-------------------+
| db1           | table1                                 |             41072 |
| db1           | table2                                 |             37839 |
| db1           | table3                                 |             36645 |
| db1           | table4                                 |             11994 |
| db1           | table5                                 |              7206 |
...
```

However the 5 tables (names changed obviously) have many more rows then that shown. There's a factor of > 1,000 larger in the tables' row count, so if this view is supposed to represent "n" scans x "r" rows in the table concerned then it looks wrong.

I'm currently using sys 1.0.1 and was checking on a MySQL 5.6.15 server.

Correctly showing the full number of rows scanned would be very good.

**Comment by MarkLeith** [comment] 2015-01-15 11:19
I can't reproduce this (see the referenced tests that I added above). 

Closing for now, but if you can generate a test that does reproduce this, please re-open the issue with the test case.

**Closed by MarkLeith** 2015-01-15 11:19 UTC
